### PR TITLE
Update schema for JNoSQL

### PR DESCRIPTION
**Pull request by rtclauss**
This is dependent on corresponding PRs in `account` and the `operator`. Please do not merge until those two PRs are also merged.

*Links to other PRs forthcoming*

### CODE REVIEW

**Comment by rtclauss** [comment]
The corresponding PR in `account` is https://github.com/IBMStockTrader/account/pull/12

**Review by jwalcorn — COMMENTED** [review]
The toString method still says _id.  Also, I moved up to 23.0.0.12 in another commit, meaning this PR now shows a merge conflict about that.  Other than those two issues, looks good.

**Comment by rtclauss** [comment]
Fixed this merge conflict. There is also a PR needed for the operator to add two new environment variables/secrets and remove an old one.  The environment variables to add are:
1. `CLOUDANT_HOST`
2. `CLOUDANT_PORT` 

And remove:
* `CLOUDANT_URL` - this is [used by](https://github.com/search?q=org%3AIBMStockTrader%20CLOUDANT_URL&type=code) both `account` and `collector` but we really don't use `collector` anymore.

I'll open an issue in the operator for this work.

**Comment by rtclauss** [comment]
Also depends on https://github.com/IBMStockTrader/account/pull/12

**Pull request merged**
